#!/usr/bin/env python3

from concurrent.futures import ThreadPoolExecutor
import glob
import subprocess
import sys

def runConf(filename):
    return subprocess.run(['certoraRun', '--server', 'production', '--prover_version', 'master', '--wait_for_results', 'all', filename],
                          capture_output = True)

confs = glob.glob('certora/conf/**/*.conf', recursive=True)
with ThreadPoolExecutor(max_workers=10) as executor:
    results = map(runConf, confs)

failed = []
for res in results:
    print(f'Checking {res.args[-1]}')
    if res.stdout != b'':
        print(res.stdout.decode().strip())
    if res.stderr != b'':
        print(res.stderr.decode().strip())
    if res.returncode == 0:
        print(f'Is okay')
    else:
        print(f'Failed with {res.returncode}')
        failed.append(res)

if failed:
    print('Some jobs failed:')
    for f in failed:
        print(f'\t{f.args[-1]}')
    sys.exit(1)
sys.exit(0)